apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - ./namespace.yaml
  - ./install.yaml

patches:
  - target:
      kind: Service
      name: argocd-server
    patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: argocd-server
      spec:
        ports:
          - name: https
            nodePort: 30520
            port: 443
            protocol: TCP
            targetPort: 8080
        type: NodePort